id: hello-world
namespace: tutorial
labels:
  name: Hello World

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley

tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    description: Return two sample values used later in the greeting.
    format: thrilled

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    description: Run quick shell commands and expose a value as output.
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'

  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    description: Log a welcome message using the inputs and earlier outputs.
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value }} to have you here!

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 9 * * *
    disabled: true

description: |
  # Flow Description
  **Use case:** Intro to Kestra that collects a `user` input and writes a friendly log.
  **Highlights:**
  - Emit sample values to demonstrate how outputs travel between tasks.
  - Run a shell command and surface its output for downstream use.
  - Log the combined greeting using both inputs and prior outputs.
  **Schedule:** Disabled daily run at 09:00—left in place to show how scheduling works.
